import React from "react";
import type { Metadata } from "next";
import "@styles/scss/main.scss";
import Header from "@widgets/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="pt-[95px]">{children}</div>
      </body>
    </html>
  );
}
